DROP TABLE IF EXISTS ACCOUNT;

CREATE TABLE ACCOUNT (
	ID DOUBLE AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
	CURRENCY VARCHAR(5) NOT NULL,
	BALANCE DOUBLE NOT NULL,
	TREASURY BOOL DEFAULT(FALSE)
);
INSERT INTO ACCOUNT (NAME,CURRENCY,BALANCE,TREASURY) VALUES 
	('TOMASA PINO MENDEZ','EUR',-5000,'1'),
	('SORAYA MORAL MENA','EUR',-1500,'1');
INSERT INTO ACCOUNT (NAME,CURRENCY,BALANCE) VALUES 
	('JULIA ROMERA ROBLES','EUR',3000),
	('DAMIAN HEREDIA PASTOR','EUR',4000),
	('MARIA AMPARO LIN LAZARO','EUR',5000);